micronaut:
  application:
    name: travelKafkaMicro
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 0.1
kafka.bootstrap.servers: localhost:9092
